@startuml

@startuml
actor Client_1
actor Client_2
boundary Network_Worker
control Client_IO_1
control auth_manager
control account_manager
database credentials
database accounts

activate Network_Worker
Network_Worker -> Client_IO_1 ++: Start

==Initiate==
deactivate Network_Worker
deactivate Client_IO_1
...Waiting for requests...

Client_1 -> Network_Worker ++: Initiate Connection
Network_Worker -> Network_Worker : Check for requests



Network_Worker -> Client_IO_1 ++: Pass connection
deactivate Network_Worker
Client_IO_1 -> Client_IO_1 : Check for requests


Client_IO_1 -> Client_1: Get Auth Details
deactivate Client_IO_1

...Waiting for requests...
Client_1 -> Client_IO_1 ++: Send Auth Credentials
Client_IO_1 -> Client_IO_1 : Check for requests

Client_IO_1 -> auth_manager ++: Verify Credentials
auth_manager -> auth_manager : Check for requests
auth_manager <-> credentials : Check Credentials
return Credentials
Client_IO_1 -> Client_1 : Logged in
deactivate Client_IO_1

...Waiting for requests...

Client_2 -> Network_Worker ++: Initiate Connection
Network_Worker -> Network_Worker : Check for requests



Network_Worker -> Client_IO_1 ++: Pass connection
deactivate Network_Worker
Client_IO_1 -> Client_IO_1 : Check for requests


Client_IO_1 -> Client_2: Get Auth Details
deactivate Client_IO_1

...Waiting for requests...
Client_2 -> Client_IO_1 ++: Send Auth Credentials
Client_IO_1 -> Client_IO_1 : Check for requests

Client_IO_1 -> auth_manager ++: Verify Credentials
auth_manager -> auth_manager : Check for requests
auth_manager <-> credentials : Check Credentials
return Credentials
Client_IO_1 -> Client_2 : Logged in
deactivate Client_IO_1

...Waiting for requests...


Client_1 -> Client_IO_1 ++: Get accounts
Client_IO_1 -> Client_IO_1 : Check for requests

Client_IO_1 -> account_manager ++:Get account details
account_manager <-> accounts :Get Data
return Account details
return Accounts

deactivate Client_IO_1
deactivate Client_1
@enduml

@enduml